#!/usr/bin/env bash
# Block edits to GENERATED asm/ and assets/ — they are regenerated by
# `make extract` and every edit is silently thrown away.
#
# asm/ can hold two categories, and only the first exists today:
#
#   (a) GENERATED PLACEHOLDERS — asm/nonmatchings/ and every plain `asm`
#       segment. splat rewrites these on every extract (and `make extract`
#       deletes the nonmatchings tree outright), so editing them is pointless
#       AND misleading: the change survives long enough to look like it worked.
#       BLOCKED, which is the case this hook exists for.
#
#   (b) AUTHORED SOURCE — `hasm` segments, holding assembly that was NEVER
#       compiled from C in the retail build. There is no C form to decompile
#       it to, so it is FINISHED rather than pending. splat writes an `hasm`
#       file only when it is MISSING and never overwrites it, which is what
#       makes annotating it worthwhile. ALLOWED.
#
# There are no `hasm` segments yet. When the first one is added, THREE places
# must change together: the splat yaml, the .gitignore negations, and the
# allowlist below. Forgetting this file shows up as a confusing BLOCKED message
# on a file you are supposed to be able to edit.
input=$(cat)
path=$(echo "$input" | python3 -c \
    "import json,sys; print(json.load(sys.stdin).get('tool_input',{}).get('file_path',''))" \
    2>/dev/null)

# --- hasm allowlist (keep in sync with the splat yaml and .gitignore) -------
case "$path" in
  # (none yet)
  __never_matches__) exit 0;;
esac

case "$path" in
  */asm/*|asm/*|*/assets/*|assets/*)
    echo "BLOCKED: this file is GENERATED from disk/SLPS_017.62 by splat and is rewritten on every 'make extract' (the nonmatchings tree is deleted outright). Editing it does nothing. To rename a symbol use config/symbols.slps01762.pepsiman.txt; to change segmentation edit config/splat.slps01762.pepsiman.yaml; then run make extract. Hand-written 'hasm' segments would be editable authored source, but none exist yet." >&2
    exit 2;;
esac
exit 0
