#!/usr/bin/env python3
"""Build an m2c context file for a src unit, and optionally run m2c on a target.

    tools/m2ctx.py DreamSys
    tools/m2ctx.py DreamSys --sig 'void DreamSys__TimerTick(DreamSys *self)'
    tools/m2ctx.py DreamSys --sig '...' --run
    tools/m2ctx.py DreamSys --run asm/nonmatchings/DreamSys/DreamSys__TimerTick.s

ALWAYS PASS --sig. m2c types a function's arguments from *a declaration of that
function*, and an INCLUDE_ASM'd function has none -- the macro expands to
nothing under -DM2CTX. Without a signature you get

    void DreamSys__TimerTick(void *arg0, ? arg1) { arg0->unk8 = -1; ... }

no matter how good the context is. With one you get real parameter names and
real field names, and the failures become informative: a `padNN[0x..]` access
in the output means the struct you guessed is MISSING A FIELD at that offset,
so a wrong guess is itself a layout measurement. Iterate on --sig until the
padding accesses disappear.

The context is DECLARATIONS ONLY. m2c never needs function bodies, and bodies
are what make its pycparser choke.
"""
import argparse
import re
import subprocess
import sys
from pathlib import Path

import srcpath

ROOT = Path(__file__).resolve().parent.parent
CPP = ROOT / "tools/gcc263/cpp"
M2C = ROOT / "tools/m2c/m2c.py"
PYTHON = ROOT / ".venv/bin/python3"
DEFAULT_OUT = ROOT / "build/ctx.c"

# The same defines the real build uses, plus M2CTX so include_asm.h expands
# INCLUDE_ASM to nothing. Using the BUILD's preprocessor and the BUILD's
# defines is the point: a context assembled by a different cpp can disagree
# with what the compiler actually sees, and then m2c's output is wrong in a way
# that looks like a struct problem.
CPP_ARGS = [
    "-Iinclude", "-Iinclude/psyq", "-undef", "-lang-c", "-nostdinc",
    "-DM2CTX",
    "-Dmips", "-D__GNUC__=2", "-D__OPTIMIZE__", "-D__mips__", "-D__mips",
    "-Dpsx", "-D__psx__", "-D__psx", "-D_PSYQ", "-D__EXTENSIONS__",
    "-D_MIPSEL", "-D_LANGUAGE_C", "-DLANGUAGE_C",
]

# pycparser understands C89 declarations and nothing else. cpp line markers,
# inline asm, and the bare `;` left behind by an `INCLUDE_ASM(...);` whose
# macro expands to nothing under -DM2CTX are all things it has no reason to
# see. The bare semicolon is not an error today, but it is not valid C89 at
# file scope and nothing obliges pycparser to keep accepting it.
DROP_LINE = re.compile(
    r"^\s*(#|__asm__|asm\s*\(|\.include|;\s*$)")


def strip_for_pycparser(text):
    """Make preprocessed output digestible: drop line markers and inline asm.

    Also drops function BODIES at file scope. m2c wants types and prototypes;
    a body only gives its parser more to reject.
    """
    out = []
    depth = 0
    for line in text.split("\n"):
        if DROP_LINE.match(line):
            continue
        if depth == 0 and re.match(r"^\w[^;=]*\)\s*\{\s*$", line):
            # A function definition at file scope: keep the signature, drop
            # the body, so the declaration still informs m2c. If cpp already
            # split the signature off onto earlier lines there is nothing left
            # to keep -- emit nothing rather than a bare `;`, which is not
            # valid C89 at file scope and which pycparser is entitled to
            # reject even though it currently tolerates it.
            sig = line[:line.rindex("{")].rstrip()
            if sig:
                out.append(sig + ";")
            depth = 1
            continue
        if depth:
            depth += line.count("{") - line.count("}")
            continue
        out.append(line)
    return "\n".join(out)


def build_context(unit_path, sigs, verbose=False):
    res = subprocess.run([str(CPP)] + CPP_ARGS + [str(unit_path)],
                         capture_output=True, text=True)
    if res.returncode != 0:
        sys.exit(f"cpp failed on {unit_path}:\n{res.stderr}")
    if verbose and res.stderr.strip():
        print(res.stderr, file=sys.stderr)

    body = strip_for_pycparser(res.stdout)

    header = [
        "/* Generated by tools/m2ctx.py -- do not edit, do not commit. */",
        f"/* context for {unit_path.relative_to(ROOT)} */",
        "",
    ]
    footer = []
    if sigs:
        footer = ["", "/* --sig: the target's own prototype. Without this m2c",
                  "   types every argument as `void *` and every field as",
                  "   `->unkNN`. */"]
        for s in sigs:
            s = s.strip().rstrip(";")
            footer.append(f"{s};")
    return "\n".join(header) + body + "\n".join(footer) + "\n"


def target_from_sig(sig):
    """The function name out of a prototype, for --run."""
    m = re.search(r"(\w+)\s*\(", sig)
    return m.group(1) if m else None


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("unit", nargs="?", help="unit name, e.g. DreamSys")
    ap.add_argument("--sig", action="append", default=[],
                    help="prototype for the target (repeatable). ALWAYS pass "
                         "one; see the module docstring for why.")
    ap.add_argument("--run", nargs="?", const=True, default=False,
                    help="run m2c afterwards, on the .s implied by --sig or "
                         "on an explicit path")
    ap.add_argument("-o", "--out", default=str(DEFAULT_OUT))
    ap.add_argument("-v", "--verbose", action="store_true")
    args = ap.parse_args()

    if not args.unit:
        ap.error("give a unit name (tools/srcpath.py lists them)")

    unit_path = srcpath.unit_src(args.unit)
    if unit_path is None:
        sys.exit(f"no such unit: {args.unit}\n"
                 f"known units: {', '.join(srcpath.units())}")

    ctx = build_context(unit_path, args.sig, args.verbose)
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(ctx)
    print(f"wrote {out} ({len(ctx.splitlines())} lines)")

    if not args.run:
        return 0

    if args.run is True:
        if len(args.sig) != 1:
            sys.exit("--run without a path needs exactly one --sig, to know "
                     "which function to decompile.")
        target = target_from_sig(args.sig[0])
        if not target:
            sys.exit(f"could not read a function name out of: {args.sig[0]}")
        found = srcpath.nm_find(target)
        if not found:
            sys.exit(f"no asm/nonmatchings/**/{target}.s — is it matched "
                     f"already, or spelled differently?")
        asm = found[0]
    else:
        asm = Path(args.run)

    cmd = [str(PYTHON), str(M2C), "-P", "4", "--target", "mipsel-gcc-c",
           "--context", str(out), str(asm)]
    print(f"$ {' '.join(cmd)}\n", file=sys.stderr)
    return subprocess.run(cmd).returncode


if __name__ == "__main__":
    sys.exit(main())
