#!/usr/bin/env bash
# Provision a decomp-permuter directory for one function.
#
#   tools/setup-permuter.sh <func> <seed.c> [outdir]
#
# <seed.c> is a small C file holding the project #includes plus ONE function
# definition -- the near-miss body, normally copied out of that function's
# match report. <outdir> defaults to permuter-work/<func> (gitignored).
#
# Then:
#   PATH=$PWD/permuter-work/bin:$PATH \
#     .venv/bin/python3 tools/decomp-permuter/permuter.py \
#       -j 6 --stop-on-zero --best-only permuter-work/<func>
#
# WHY THIS SCRIPT EXISTS. Setting this up by hand hits five traps that each
# look like a broken toolchain. The first four cost real time in round 8
# (2026-09-02) and the fifth in round 19; they are fixed here so nobody pays
# twice:
#
#   1. `prelude.inc` ends with `.set gp=64`, and our `as` rejects that against
#      an r3000: "`gp=64' used with a 32-bit processor". Dropped below.
#   2. The permuter's scorer shells out to `mips-linux-gnu-objdump`, hardcoded.
#      Ours is `mipsel-linux-gnu-objdump`. A PATH shim directory of symlinks
#      fixes it WITHOUT touching the vendored permuter or the build -- see
#      permuter-work/bin, created here.
#   3. maspsx emits `.include "include/labels.inc"`, a REPO-RELATIVE path, but
#      the permuter runs compile.sh from its own directory. compile.sh
#      therefore passes `-I$REPO` as well as `-I$REPO/include`.
#   4. `strip_other_fns.py` prunes typedefs it thinks are unused. The permuter
#      itself copes, but a hand-rolled scoring harness built on the stripped
#      base.c will die with "parse error before `*'" on the target's own
#      return type. Score candidates against the REAL headers instead.
#   5. A seed carrying the permuter's own PERM_* macros cannot be validated by
#      the real cc1 at all -- cc1 has never heard of them, and the parse error
#      reads like a broken seed. The scaffold build is skipped for such seeds,
#      with the permuter's own parser named as the validator. See TRAP 5 below.
#
# THE COMPILE PIPELINE HERE IS THE MAKEFILE'S, VERBATIM. The permuter mutates
# SOURCE under a fixed toolchain -- that is why using it is not a toolchain
# change, and it stops being true the moment these flags drift from
# Makefile:113. If you change one, you are no longer permuting this project.
set -euo pipefail
cd "$(dirname "$0")/.."
REPO=$(pwd)

func=${1:?usage: setup-permuter.sh <func> <seed.c> [outdir]}
seed=${2:?usage: setup-permuter.sh <func> <seed.c> [outdir]}
dir=${3:-permuter-work/$func}

[ -f "$seed" ] || { echo "FATAL: no such seed file: $seed" >&2; exit 1; }

# Find the function's disassembly without being told which unit it is in.
asm=$(find asm/nonmatchings -name "$func.s" -print -quit)
[ -n "$asm" ] || { echo "FATAL: no asm/nonmatchings/**/$func.s -- is it already matched?" >&2; exit 1; }
echo "target asm: $asm"

mkdir -p "$dir" permuter-work/bin

# Trap 2: the scorer's hardcoded tool names.
for t in objdump as; do
    ln -sf "$REPO/tools/binutils/bin/mipsel-linux-gnu-$t" "permuter-work/bin/mips-linux-gnu-$t"
done

# --- compile.sh: Makefile's C rule, with trap 3's extra -I ------------------
# Trap 7 (round 43): this file used to hardcode its own copy of MASPSX_FLAGS.
# Round 42 added --gp-symbols and --no-nop-mflo-mfhi to the Makefile and the
# copy here silently kept the old list, so every permuter base.o for a
# gp_rel- or mflo-touching function was miscompiled against a correct
# target.o -- base scores in the thousands, and search negatives that meant
# nothing. Read the list FROM the Makefile instead; a repo-relative path in it
# (config/gp-symbols.txt) is made absolute because compile.sh runs from the
# permuter's own cwd.
MASPSX_FLAGS=$(sed -n 's/^MASPSX_FLAGS *:= *//p' "$REPO/Makefile" | sed "s| config/| $REPO/config/|g; s|=config/|=$REPO/config/|g")
[ -n "$MASPSX_FLAGS" ] || { echo "FATAL: could not read MASPSX_FLAGS from $REPO/Makefile" >&2; exit 1; }
echo "maspsx flags (from Makefile): $MASPSX_FLAGS"
# Trap 8: CC_FLAGS were hardcoded here too, with -G0 while the Makefile has
# -G8 (Pepsiman's 2.8.1 splits %hi/%lo itself). The scaffold then disagreed
# with funcdiff on the same body. Read them from the Makefile like MASPSX_FLAGS.
CC_FLAGS=$(sed -n 's/^CC_FLAGS *[:+]\{0,1\}= *//p' "$REPO/Makefile" | tr '\n' ' ')
[ -n "$CC_FLAGS" ] || { echo "FATAL: could not read CC_FLAGS from $REPO/Makefile" >&2; exit 1; }
echo "cc1 flags (from Makefile): $CC_FLAGS"
cat > "$dir/compile.sh" <<SH
#!/bin/bash
# GENERATED by tools/setup-permuter.sh -- the Makefile's C rule, verbatim.
set -euo pipefail
REPO=$REPO
CPP_FLAGS="-I\$REPO/include -I\$REPO/include/psyq -undef -Wall -lang-c -nostdinc
 -Dmips -D__GNUC__=2 -D__OPTIMIZE__ -D__mips__ -D__mips -Dpsx -D__psx__ -D__psx
 -D_PSYQ -D__EXTENSIONS__ -D_MIPSEL -D_LANGUAGE_C -DLANGUAGE_C"
CC_FLAGS="$CC_FLAGS"
MASPSX_FLAGS="$MASPSX_FLAGS"
# -I\$REPO is trap 3: maspsx emits a repo-relative .include "include/labels.inc"
AS_FLAGS="-I\$REPO -I\$REPO/include -I\$REPO/include/psyq -march=r3000
 -mtune=r3000 -EL -no-pad-sections -G0 -O2"
INPUT=\$1; shift
\$REPO/tools/gcc/cpp \$CPP_FLAGS "\$INPUT" \\
  | \$REPO/tools/gcc/cc1 \$CC_FLAGS \\
  | \$REPO/.venv/bin/python3 \$REPO/tools/maspsx/maspsx.py \$MASPSX_FLAGS \\
  | \$REPO/tools/binutils/bin/mipsel-linux-gnu-as \$AS_FLAGS "\$@"
SH
chmod +x "$dir/compile.sh"

printf 'func_name = "%s"\ncompiler_type = "gcc"\n' "$func" > "$dir/settings.toml"

# --- target.o: retail's own bytes -------------------------------------------
# Trap 1: drop `.set gp=64`. Drop splat's own `.set noat`/`.set noreorder`
# too -- prelude.inc supplies both at its lines 1-2, so they are redundant.
#
# Trap 6 (found round 24): this used to be `sed -e '1,4d'`, deleting the first
# FOUR lines by POSITION. For an ordinary function those are exactly
# `.set noat`, `.set noreorder`, a blank, and `nonmatching <func>, 0xNN`, so it
# looked right. But a function that OWNS EMBEDDED RODATA has `.section .rodata`
# as its line 4 -- splat emits the jump table before the text -- and deleting
# that line silently assembles the table into `.text`. target.o then does not
# hold retail's bytes at all, and the permuter's objdump parser crashes on it.
# Delete by CONTENT instead, and keep `nonmatching`: prelude.inc defines that
# macro (line 43), so it is fine anywhere after the prelude.
grep -v '^\.set gp=64' tools/decomp-permuter/prelude.inc > "$dir/target.s"
sed -e '/^\.set noat/d' -e '/^\.set noreorder/d' "$asm" >> "$dir/target.s"
tools/binutils/bin/mipsel-linux-gnu-as -march=r3000 -mtune=r3000 -EL \
    -no-pad-sections -G0 -O2 "$dir/target.s" -o "$dir/target.o"

# --- base.c: the seed, preprocessed and reduced to one function -------------
cp "$seed" "$dir/orig.c"
tools/gcc/cpp -Iinclude -Iinclude/psyq -undef -lang-c -nostdinc \
  -Dmips -D__GNUC__=2 -D__OPTIMIZE__ -D__mips__ -D__mips -Dpsx -D__psx__ -D__psx \
  -D_PSYQ -D__EXTENSIONS__ -D_MIPSEL -D_LANGUAGE_C -DLANGUAGE_C \
  -D'__attribute__(x)=' "$dir/orig.c" | grep -v '^#' > "$dir/base.c"
.venv/bin/python3 tools/decomp-permuter/strip_other_fns.py "$dir/base.c" "$func"

# --- prove the scaffold before handing it over ------------------------------
# A permuter dir whose base does not even compile wastes a whole search, and
# one whose base score is not the score the match report claims is scoring
# something other than the function you think it is.
#
# TRAP 5 (round 19): a seed carrying decomp-permuter's own PERM_* macros CANNOT
# be validated this way, and the failure is opaque. Those macros are read by the
# permuter's pycparser front end, which expands them into concrete variants; the
# real `cc1` has never heard of them and dies on a parse error that reads like a
# broken seed. Several match reports recommend a "hinted PERM_GENERAL search" as
# the next step, and following that advice used to make this script fail with no
# hint as to why. Detect it and say so instead.
if grep -qE '\bPERM_[A-Z]+[A-Z_]*[[:space:]]*\(' "$dir/base.c"; then
    echo
    echo "NOTE: this seed uses decomp-permuter PERM_* macros, so the real cc1"
    echo "      cannot parse it and the usual scaffold build is SKIPPED."
    echo "      That is expected, not a broken seed -- PERM_* is read by the"
    echo "      permuter's own parser, which substitutes concrete variants"
    echo "      before any compile happens."
    echo
    echo "      Validate it with the permuter itself, which runs that parser:"
    echo
    echo "        PATH=$REPO/permuter-work/bin:\$PATH \\"
    echo "          .venv/bin/python3 tools/decomp-permuter/permuter.py --debug --stack-diffs $dir"
    echo
    echo "      A parse error there is a real problem with the seed; silence is"
    echo "      a working scaffold. Note the base score it prints is in PERMUTER"
    echo "      units (a weighted penalty), NOT a word count -- check it against"
    echo "      the match report's residue before trusting the scaffold."
    echo
else
    "$dir/compile.sh" "$dir/base.c" -o "$dir/base.o"
fi
echo
if [ -f "$dir/base.o" ]; then
    echo "scaffold built in $dir -- base compiles, target assembled."
else
    echo "scaffold built in $dir -- target assembled; base NOT compiled (PERM_* seed, see note above)."
fi
echo "Sanity-check the base score against the match report BEFORE searching:"
echo
echo "  PATH=$REPO/permuter-work/bin:\$PATH \\"
echo "    .venv/bin/python3 tools/decomp-permuter/permuter.py --debug --stack-diffs $dir"
echo
echo "Then search (a zero is a LEAD -- translate it to idiomatic C and"
echo "re-verify with ./build-and-verify.sh plus tools/funcdiff.py):"
echo
echo "  PATH=$REPO/permuter-work/bin:\$PATH \\"
echo "    .venv/bin/python3 tools/decomp-permuter/permuter.py -j 6 \\"
echo "      --stop-on-zero --best-only $dir"
